# Generated by Django 2.0.6 on 2018-06-11 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Superman')),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=2)),
                ('email', models.EmailField(default='default@default.com', max_length=254)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('job', models.TextField(default='Knight')),
            ],
        ),
    ]
