# Generated by Django 2.0.6 on 2018-06-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='name',
            field=models.CharField(default='Superman', max_length=50),
        ),
    ]
